---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build:
    name: Build the lib with Idris2 HEAD
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build lib
        run: pack --no-prompt build tui
      - name: Build gallery
        run: pack --no-prompt build gallery
      - name: Build scrollclip
        run: pack --no-prompt build scrollclip
      - name: Build todo
        run: pack --no-prompt build todo
      - name: Build user_event
        run: pack --no-prompt build user_event
